//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Personal.WebHost.Report {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dtsPersonal")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dtsPersonal : global::System.Data.DataSet {
        
        private RRHH_SP_RPT_LISTAR_PERSONALDataTable tableRRHH_SP_RPT_LISTAR_PERSONAL;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public dtsPersonal() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected dtsPersonal(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["RRHH_SP_RPT_LISTAR_PERSONAL"] != null)) {
                    base.Tables.Add(new RRHH_SP_RPT_LISTAR_PERSONALDataTable(ds.Tables["RRHH_SP_RPT_LISTAR_PERSONAL"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RRHH_SP_RPT_LISTAR_PERSONALDataTable RRHH_SP_RPT_LISTAR_PERSONAL {
            get {
                return this.tableRRHH_SP_RPT_LISTAR_PERSONAL;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dtsPersonal cln = ((dtsPersonal)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["RRHH_SP_RPT_LISTAR_PERSONAL"] != null)) {
                    base.Tables.Add(new RRHH_SP_RPT_LISTAR_PERSONALDataTable(ds.Tables["RRHH_SP_RPT_LISTAR_PERSONAL"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableRRHH_SP_RPT_LISTAR_PERSONAL = ((RRHH_SP_RPT_LISTAR_PERSONALDataTable)(base.Tables["RRHH_SP_RPT_LISTAR_PERSONAL"]));
            if ((initTable == true)) {
                if ((this.tableRRHH_SP_RPT_LISTAR_PERSONAL != null)) {
                    this.tableRRHH_SP_RPT_LISTAR_PERSONAL.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dtsPersonal";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dtsPersonal.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRRHH_SP_RPT_LISTAR_PERSONAL = new RRHH_SP_RPT_LISTAR_PERSONALDataTable();
            base.Tables.Add(this.tableRRHH_SP_RPT_LISTAR_PERSONAL);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeRRHH_SP_RPT_LISTAR_PERSONAL() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dtsPersonal ds = new dtsPersonal();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void RRHH_SP_RPT_LISTAR_PERSONALRowChangeEventHandler(object sender, RRHH_SP_RPT_LISTAR_PERSONALRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class RRHH_SP_RPT_LISTAR_PERSONALDataTable : global::System.Data.TypedTableBase<RRHH_SP_RPT_LISTAR_PERSONALRow> {
            
            private global::System.Data.DataColumn columnROW;
            
            private global::System.Data.DataColumn columnC_COD_PERSONA;
            
            private global::System.Data.DataColumn columnI_COD_INSTANCIA;
            
            private global::System.Data.DataColumn columnV_DES_INSTANCIA;
            
            private global::System.Data.DataColumn columnTITULO_INSTITUCION;
            
            private global::System.Data.DataColumn columnINSTITUCION;
            
            private global::System.Data.DataColumn columnV_DES_TIPO_EMPLEADO;
            
            private global::System.Data.DataColumn columnI_COD_TIPO_MODALIDAD;
            
            private global::System.Data.DataColumn columnI_COD_TIPO_EMPLEADO;
            
            private global::System.Data.DataColumn columnGRADO;
            
            private global::System.Data.DataColumn columnDNI;
            
            private global::System.Data.DataColumn columnARMA;
            
            private global::System.Data.DataColumn columnEMPLEADO;
            
            private global::System.Data.DataColumn columnAREA;
            
            private global::System.Data.DataColumn columnCARGO;
            
            private global::System.Data.DataColumn columnSEXO;
            
            private global::System.Data.DataColumn columnC_ACTIVO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RRHH_SP_RPT_LISTAR_PERSONALDataTable() {
                this.TableName = "RRHH_SP_RPT_LISTAR_PERSONAL";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal RRHH_SP_RPT_LISTAR_PERSONALDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected RRHH_SP_RPT_LISTAR_PERSONALDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ROWColumn {
                get {
                    return this.columnROW;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn C_COD_PERSONAColumn {
                get {
                    return this.columnC_COD_PERSONA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn I_COD_INSTANCIAColumn {
                get {
                    return this.columnI_COD_INSTANCIA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn V_DES_INSTANCIAColumn {
                get {
                    return this.columnV_DES_INSTANCIA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TITULO_INSTITUCIONColumn {
                get {
                    return this.columnTITULO_INSTITUCION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn INSTITUCIONColumn {
                get {
                    return this.columnINSTITUCION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn V_DES_TIPO_EMPLEADOColumn {
                get {
                    return this.columnV_DES_TIPO_EMPLEADO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn I_COD_TIPO_MODALIDADColumn {
                get {
                    return this.columnI_COD_TIPO_MODALIDAD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn I_COD_TIPO_EMPLEADOColumn {
                get {
                    return this.columnI_COD_TIPO_EMPLEADO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn GRADOColumn {
                get {
                    return this.columnGRADO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DNIColumn {
                get {
                    return this.columnDNI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ARMAColumn {
                get {
                    return this.columnARMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn EMPLEADOColumn {
                get {
                    return this.columnEMPLEADO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AREAColumn {
                get {
                    return this.columnAREA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CARGOColumn {
                get {
                    return this.columnCARGO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SEXOColumn {
                get {
                    return this.columnSEXO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn C_ACTIVOColumn {
                get {
                    return this.columnC_ACTIVO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RRHH_SP_RPT_LISTAR_PERSONALRow this[int index] {
                get {
                    return ((RRHH_SP_RPT_LISTAR_PERSONALRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event RRHH_SP_RPT_LISTAR_PERSONALRowChangeEventHandler RRHH_SP_RPT_LISTAR_PERSONALRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event RRHH_SP_RPT_LISTAR_PERSONALRowChangeEventHandler RRHH_SP_RPT_LISTAR_PERSONALRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event RRHH_SP_RPT_LISTAR_PERSONALRowChangeEventHandler RRHH_SP_RPT_LISTAR_PERSONALRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event RRHH_SP_RPT_LISTAR_PERSONALRowChangeEventHandler RRHH_SP_RPT_LISTAR_PERSONALRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddRRHH_SP_RPT_LISTAR_PERSONALRow(RRHH_SP_RPT_LISTAR_PERSONALRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RRHH_SP_RPT_LISTAR_PERSONALRow AddRRHH_SP_RPT_LISTAR_PERSONALRow(
                        int ROW, 
                        string C_COD_PERSONA, 
                        int I_COD_INSTANCIA, 
                        string V_DES_INSTANCIA, 
                        string TITULO_INSTITUCION, 
                        string INSTITUCION, 
                        string V_DES_TIPO_EMPLEADO, 
                        int I_COD_TIPO_MODALIDAD, 
                        int I_COD_TIPO_EMPLEADO, 
                        string GRADO, 
                        string DNI, 
                        string ARMA, 
                        string EMPLEADO, 
                        string AREA, 
                        string CARGO, 
                        string SEXO, 
                        string C_ACTIVO) {
                RRHH_SP_RPT_LISTAR_PERSONALRow rowRRHH_SP_RPT_LISTAR_PERSONALRow = ((RRHH_SP_RPT_LISTAR_PERSONALRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ROW,
                        C_COD_PERSONA,
                        I_COD_INSTANCIA,
                        V_DES_INSTANCIA,
                        TITULO_INSTITUCION,
                        INSTITUCION,
                        V_DES_TIPO_EMPLEADO,
                        I_COD_TIPO_MODALIDAD,
                        I_COD_TIPO_EMPLEADO,
                        GRADO,
                        DNI,
                        ARMA,
                        EMPLEADO,
                        AREA,
                        CARGO,
                        SEXO,
                        C_ACTIVO};
                rowRRHH_SP_RPT_LISTAR_PERSONALRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRRHH_SP_RPT_LISTAR_PERSONALRow);
                return rowRRHH_SP_RPT_LISTAR_PERSONALRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                RRHH_SP_RPT_LISTAR_PERSONALDataTable cln = ((RRHH_SP_RPT_LISTAR_PERSONALDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new RRHH_SP_RPT_LISTAR_PERSONALDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnROW = base.Columns["ROW"];
                this.columnC_COD_PERSONA = base.Columns["C_COD_PERSONA"];
                this.columnI_COD_INSTANCIA = base.Columns["I_COD_INSTANCIA"];
                this.columnV_DES_INSTANCIA = base.Columns["V_DES_INSTANCIA"];
                this.columnTITULO_INSTITUCION = base.Columns["TITULO_INSTITUCION"];
                this.columnINSTITUCION = base.Columns["INSTITUCION"];
                this.columnV_DES_TIPO_EMPLEADO = base.Columns["V_DES_TIPO_EMPLEADO"];
                this.columnI_COD_TIPO_MODALIDAD = base.Columns["I_COD_TIPO_MODALIDAD"];
                this.columnI_COD_TIPO_EMPLEADO = base.Columns["I_COD_TIPO_EMPLEADO"];
                this.columnGRADO = base.Columns["GRADO"];
                this.columnDNI = base.Columns["DNI"];
                this.columnARMA = base.Columns["ARMA"];
                this.columnEMPLEADO = base.Columns["EMPLEADO"];
                this.columnAREA = base.Columns["AREA"];
                this.columnCARGO = base.Columns["CARGO"];
                this.columnSEXO = base.Columns["SEXO"];
                this.columnC_ACTIVO = base.Columns["C_ACTIVO"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnROW = new global::System.Data.DataColumn("ROW", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROW);
                this.columnC_COD_PERSONA = new global::System.Data.DataColumn("C_COD_PERSONA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnC_COD_PERSONA);
                this.columnI_COD_INSTANCIA = new global::System.Data.DataColumn("I_COD_INSTANCIA", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnI_COD_INSTANCIA);
                this.columnV_DES_INSTANCIA = new global::System.Data.DataColumn("V_DES_INSTANCIA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnV_DES_INSTANCIA);
                this.columnTITULO_INSTITUCION = new global::System.Data.DataColumn("TITULO_INSTITUCION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTITULO_INSTITUCION);
                this.columnINSTITUCION = new global::System.Data.DataColumn("INSTITUCION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINSTITUCION);
                this.columnV_DES_TIPO_EMPLEADO = new global::System.Data.DataColumn("V_DES_TIPO_EMPLEADO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnV_DES_TIPO_EMPLEADO);
                this.columnI_COD_TIPO_MODALIDAD = new global::System.Data.DataColumn("I_COD_TIPO_MODALIDAD", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnI_COD_TIPO_MODALIDAD);
                this.columnI_COD_TIPO_EMPLEADO = new global::System.Data.DataColumn("I_COD_TIPO_EMPLEADO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnI_COD_TIPO_EMPLEADO);
                this.columnGRADO = new global::System.Data.DataColumn("GRADO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGRADO);
                this.columnDNI = new global::System.Data.DataColumn("DNI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDNI);
                this.columnARMA = new global::System.Data.DataColumn("ARMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnARMA);
                this.columnEMPLEADO = new global::System.Data.DataColumn("EMPLEADO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEMPLEADO);
                this.columnAREA = new global::System.Data.DataColumn("AREA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAREA);
                this.columnCARGO = new global::System.Data.DataColumn("CARGO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCARGO);
                this.columnSEXO = new global::System.Data.DataColumn("SEXO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSEXO);
                this.columnC_ACTIVO = new global::System.Data.DataColumn("C_ACTIVO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnC_ACTIVO);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RRHH_SP_RPT_LISTAR_PERSONALRow NewRRHH_SP_RPT_LISTAR_PERSONALRow() {
                return ((RRHH_SP_RPT_LISTAR_PERSONALRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RRHH_SP_RPT_LISTAR_PERSONALRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(RRHH_SP_RPT_LISTAR_PERSONALRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RRHH_SP_RPT_LISTAR_PERSONALRowChanged != null)) {
                    this.RRHH_SP_RPT_LISTAR_PERSONALRowChanged(this, new RRHH_SP_RPT_LISTAR_PERSONALRowChangeEvent(((RRHH_SP_RPT_LISTAR_PERSONALRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RRHH_SP_RPT_LISTAR_PERSONALRowChanging != null)) {
                    this.RRHH_SP_RPT_LISTAR_PERSONALRowChanging(this, new RRHH_SP_RPT_LISTAR_PERSONALRowChangeEvent(((RRHH_SP_RPT_LISTAR_PERSONALRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RRHH_SP_RPT_LISTAR_PERSONALRowDeleted != null)) {
                    this.RRHH_SP_RPT_LISTAR_PERSONALRowDeleted(this, new RRHH_SP_RPT_LISTAR_PERSONALRowChangeEvent(((RRHH_SP_RPT_LISTAR_PERSONALRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RRHH_SP_RPT_LISTAR_PERSONALRowDeleting != null)) {
                    this.RRHH_SP_RPT_LISTAR_PERSONALRowDeleting(this, new RRHH_SP_RPT_LISTAR_PERSONALRowChangeEvent(((RRHH_SP_RPT_LISTAR_PERSONALRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveRRHH_SP_RPT_LISTAR_PERSONALRow(RRHH_SP_RPT_LISTAR_PERSONALRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dtsPersonal ds = new dtsPersonal();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "RRHH_SP_RPT_LISTAR_PERSONALDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class RRHH_SP_RPT_LISTAR_PERSONALRow : global::System.Data.DataRow {
            
            private RRHH_SP_RPT_LISTAR_PERSONALDataTable tableRRHH_SP_RPT_LISTAR_PERSONAL;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal RRHH_SP_RPT_LISTAR_PERSONALRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRRHH_SP_RPT_LISTAR_PERSONAL = ((RRHH_SP_RPT_LISTAR_PERSONALDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ROW {
                get {
                    try {
                        return ((int)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.ROWColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROW\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.ROWColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string C_COD_PERSONA {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.C_COD_PERSONAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'C_COD_PERSONA\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.C_COD_PERSONAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int I_COD_INSTANCIA {
                get {
                    try {
                        return ((int)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_INSTANCIAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'I_COD_INSTANCIA\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_INSTANCIAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string V_DES_INSTANCIA {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.V_DES_INSTANCIAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'V_DES_INSTANCIA\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.V_DES_INSTANCIAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TITULO_INSTITUCION {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.TITULO_INSTITUCIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TITULO_INSTITUCION\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.TITULO_INSTITUCIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string INSTITUCION {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.INSTITUCIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'INSTITUCION\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.INSTITUCIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string V_DES_TIPO_EMPLEADO {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.V_DES_TIPO_EMPLEADOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'V_DES_TIPO_EMPLEADO\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.V_DES_TIPO_EMPLEADOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int I_COD_TIPO_MODALIDAD {
                get {
                    try {
                        return ((int)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_TIPO_MODALIDADColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'I_COD_TIPO_MODALIDAD\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_TIPO_MODALIDADColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int I_COD_TIPO_EMPLEADO {
                get {
                    try {
                        return ((int)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_TIPO_EMPLEADOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'I_COD_TIPO_EMPLEADO\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_TIPO_EMPLEADOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string GRADO {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.GRADOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GRADO\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.GRADOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DNI {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.DNIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DNI\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.DNIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ARMA {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.ARMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ARMA\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.ARMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string EMPLEADO {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.EMPLEADOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EMPLEADO\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.EMPLEADOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string AREA {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.AREAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AREA\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.AREAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CARGO {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.CARGOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CARGO\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.CARGOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string SEXO {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.SEXOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SEXO\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.SEXOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string C_ACTIVO {
                get {
                    try {
                        return ((string)(this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.C_ACTIVOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'C_ACTIVO\' in table \'RRHH_SP_RPT_LISTAR_PERSONAL\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.C_ACTIVOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsROWNull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.ROWColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetROWNull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.ROWColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsC_COD_PERSONANull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.C_COD_PERSONAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetC_COD_PERSONANull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.C_COD_PERSONAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsI_COD_INSTANCIANull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_INSTANCIAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetI_COD_INSTANCIANull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_INSTANCIAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsV_DES_INSTANCIANull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.V_DES_INSTANCIAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetV_DES_INSTANCIANull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.V_DES_INSTANCIAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTITULO_INSTITUCIONNull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.TITULO_INSTITUCIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTITULO_INSTITUCIONNull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.TITULO_INSTITUCIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsINSTITUCIONNull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.INSTITUCIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetINSTITUCIONNull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.INSTITUCIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsV_DES_TIPO_EMPLEADONull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.V_DES_TIPO_EMPLEADOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetV_DES_TIPO_EMPLEADONull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.V_DES_TIPO_EMPLEADOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsI_COD_TIPO_MODALIDADNull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_TIPO_MODALIDADColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetI_COD_TIPO_MODALIDADNull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_TIPO_MODALIDADColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsI_COD_TIPO_EMPLEADONull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_TIPO_EMPLEADOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetI_COD_TIPO_EMPLEADONull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.I_COD_TIPO_EMPLEADOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsGRADONull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.GRADOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetGRADONull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.GRADOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDNINull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.DNIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDNINull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.DNIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsARMANull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.ARMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetARMANull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.ARMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsEMPLEADONull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.EMPLEADOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetEMPLEADONull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.EMPLEADOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAREANull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.AREAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAREANull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.AREAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCARGONull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.CARGOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCARGONull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.CARGOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSEXONull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.SEXOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSEXONull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.SEXOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsC_ACTIVONull() {
                return this.IsNull(this.tableRRHH_SP_RPT_LISTAR_PERSONAL.C_ACTIVOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetC_ACTIVONull() {
                this[this.tableRRHH_SP_RPT_LISTAR_PERSONAL.C_ACTIVOColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class RRHH_SP_RPT_LISTAR_PERSONALRowChangeEvent : global::System.EventArgs {
            
            private RRHH_SP_RPT_LISTAR_PERSONALRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RRHH_SP_RPT_LISTAR_PERSONALRowChangeEvent(RRHH_SP_RPT_LISTAR_PERSONALRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public RRHH_SP_RPT_LISTAR_PERSONALRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591