//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_AREAS
    {
        public MA_AREAS()
        {
            this.MA_INSTANCIA_AREAS = new HashSet<MA_INSTANCIA_AREAS>();
        }
    
        public string C_COD_AREA { get; set; }
        public string V_DES_FUNCIONES { get; set; }
        public string C_ACTIVO { get; set; }
        public string V_ABREV_FUNCIONES { get; set; }
    
        public virtual ICollection<MA_INSTANCIA_AREAS> MA_INSTANCIA_AREAS { get; set; }
    }
}
