//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_AÑOS
    {
        public MA_AÑOS()
        {
            this.MA_APERTURAR_AÑOS = new HashSet<MA_APERTURAR_AÑOS>();
        }
    
        public int I_COD_AÑO { get; set; }
    
        public virtual ICollection<MA_APERTURAR_AÑOS> MA_APERTURAR_AÑOS { get; set; }
    }
}
