//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_APERTURAR_AÑOS
    {
        public MA_APERTURAR_AÑOS()
        {
            this.MA_APERTURAR_MES_PEDIDO = new HashSet<MA_APERTURAR_MES_PEDIDO>();
        }
    
        public string C_COD_TIPO_SISTEMA { get; set; }
        public int I_COD_AÑO { get; set; }
        public Nullable<System.DateTime> FEC_APERTURA { get; set; }
        public string FEC_FINALIZACION { get; set; }
        public string C_ESTADO_APERTURA { get; set; }
    
        public virtual MA_AÑOS MA_AÑOS { get; set; }
        public virtual MA_TIPO_SISTEMA MA_TIPO_SISTEMA { get; set; }
        public virtual ICollection<MA_APERTURAR_MES_PEDIDO> MA_APERTURAR_MES_PEDIDO { get; set; }
    }
}
