//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ARTICULO
    {
        public MA_ARTICULO()
        {
            this.PED_PEDIDO_DETALLE = new HashSet<PED_PEDIDO_DETALLE>();
            this.PED_DET_VALE_RETIRO = new HashSet<PED_DET_VALE_RETIRO>();
            this.PED_ARTICULO_AREAS = new HashSet<PED_ARTICULO_AREAS>();
        }
    
        public string C_COD_ARTICULO { get; set; }
        public string V_DES_ARTICULO { get; set; }
        public Nullable<int> I_COD_UNIDAD_MEDIDA { get; set; }
        public Nullable<int> I_STOCK { get; set; }
        public Nullable<decimal> D_PRECIO { get; set; }
        public Nullable<System.DateTime> D_FECHA_REGISTRO { get; set; }
        public string C_ACTIVO { get; set; }
        public Nullable<int> I_COD_TIPO_ARTICULO { get; set; }
    
        public virtual MA_UNIDAD_MEDIDA MA_UNIDAD_MEDIDA { get; set; }
        public virtual ICollection<PED_PEDIDO_DETALLE> PED_PEDIDO_DETALLE { get; set; }
        public virtual MA_TIPO_ARTICULO MA_TIPO_ARTICULO { get; set; }
        public virtual ICollection<PED_DET_VALE_RETIRO> PED_DET_VALE_RETIRO { get; set; }
        public virtual ICollection<PED_ARTICULO_AREAS> PED_ARTICULO_AREAS { get; set; }
    }
}
