//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{


    using System;
    using System.ComponentModel.DataAnnotations;
    using Personal.Models;
    using System.Collections.Generic;

    [MetadataType(typeof(cargoModel))]
    public partial class MA_CARGO
    {
        public MA_CARGO()
        {
       
            this.RRHH_PERSONA_CARGO = new HashSet<RRHH_PERSONA_CARGO>();
        }

        public int I_COD_CARGO { get; set; }
        public string V_DES_CARGO { get; set; }
        public string C_ACTIVO { get; set; }


        public virtual ICollection<RRHH_PERSONA_CARGO> RRHH_PERSONA_CARGO { get; set; }
    }
}
