//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_COLOR
    {
        public MA_COLOR()
        {
            this.SG_PERSONA_VEHICULOS = new HashSet<SG_PERSONA_VEHICULOS>();
        }
    
        public int I_COD_COLOR { get; set; }
        public string V_DES_COLOR { get; set; }
        public string C_ACTIVO { get; set; }
    
        public virtual ICollection<SG_PERSONA_VEHICULOS> SG_PERSONA_VEHICULOS { get; set; }
    }
}
