//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DETALLE_RAZGOS
    {
        public MA_DETALLE_RAZGOS()
        {
            this.SG_PERSONA_RAZGOS = new HashSet<SG_PERSONA_RAZGOS>();
        }
    
        public int I_COD_DETALLE_RAZGOS { get; set; }
        public int I_COD_RAZGOS { get; set; }
        public string V_DES_DETALLE_RAZGOS { get; set; }
        public string C_ACTIVO { get; set; }
    
        public virtual MA_TIPO_RAZGOS MA_TIPO_RAZGOS { get; set; }
        public virtual ICollection<SG_PERSONA_RAZGOS> SG_PERSONA_RAZGOS { get; set; }
    }
}
