//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ESTADO_PEDIDO
    {
        public MA_ESTADO_PEDIDO()
        {
            this.PED_PEDIDO_ESTADO = new HashSet<PED_PEDIDO_ESTADO>();
            this.PED_CAB_ESTADO_VALE = new HashSet<PED_CAB_ESTADO_VALE>();
        }
    
        public string I_COD_ESTADO_PEDIDO { get; set; }
        public string V_DES_ESTADO { get; set; }
    
        public virtual ICollection<PED_PEDIDO_ESTADO> PED_PEDIDO_ESTADO { get; set; }
        public virtual ICollection<PED_CAB_ESTADO_VALE> PED_CAB_ESTADO_VALE { get; set; }
    }
}
