//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using Personal.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(maEstadoCivilModel))]
    public partial class MA_ESTADO_CIVIL
    {
        public MA_ESTADO_CIVIL()
        {
            this.RRHH_PERSONA_DETALLE = new HashSet<RRHH_PERSONA_DETALLE>();
        }

        public int I_COD_ESTADO_CIVIL { get; set; }
        public string V_DES_ESTADO_CIVIL { get; set; }
        public string C_ACTIVO { get; set; }

        public virtual ICollection<RRHH_PERSONA_DETALLE> RRHH_PERSONA_DETALLE { get; set; }
    }
}
