//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using Personal.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(gradoMilitarModel))]
    public partial class MA_GRADO_MILITAR
    {
        public MA_GRADO_MILITAR()
        {
            this.MA_INSTITUCION = new MA_INSTITUCION();
            this.RRHH_PERSONA_GRADO = new HashSet<RRHH_PERSONA_GRADO>();
        }
    
        public string C_COD_GRADO_MILITAR { get; set; }
        public string V_DES_GRADO { get; set; }
        public string C_ATIVO { get; set; }
        public string V_ABREV_GRADOS { get; set; }
        public int I_COD_INSTITUCION { get; set; }
    
        public virtual MA_INSTITUCION MA_INSTITUCION { get; set; }
        public virtual ICollection<RRHH_PERSONA_GRADO> RRHH_PERSONA_GRADO { get; set; }
    }
}
