//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{


    using System;
    using System.ComponentModel.DataAnnotations;
    using Personal.Models;
    using System.Collections.Generic;
    using System.Data.Spatial;


    [MetadataType(typeof(instanciaModel))]
    public partial class MA_INSTANCIA
    {
        public MA_INSTANCIA()
        {
            this.MA_INSTANCIA_AREAS = new HashSet<MA_INSTANCIA_AREAS>();
            this.MA_INSTANCIA1 = new HashSet<MA_INSTANCIA>();
            this.SG_PERSONA_TRABAJOS = new HashSet<SG_PERSONA_TRABAJO>();

        }

        public string I_COD_INSTANCIA { get; set; }
        public string I_COD_INSTANCIA_SUPERIOR { get; set; }
        public string V_ABREV_INSTANCIA { get; set; }
        public string C_ACTIVO { get; set; }
        public Nullable<int> I_CANT_INSTANCIA { get; set; }
        public string V_DES_INSTANCIA { get; set; }
        public string C_COD_DISTRITO { get; set; }
        public Nullable<int> I_COD_PAIS { get; set; }
        public string C_COD_PROVINCIA { get; set; }
        public string C_COD_DEPARTAMENTO { get; set; }
        public string V_DES_DIRECCION { get; set; }
        //public DbGeography V_GEO_LOCALIZACION { get; set; }
        public string V_GEO_LOCALIZACION { get; set; }
        public Nullable<int> I_COD_INSTITUCION { get; set; }

        public virtual ICollection<MA_INSTANCIA_AREAS> MA_INSTANCIA_AREAS { get; set; }
        public virtual ICollection<MA_INSTANCIA> MA_INSTANCIA1 { get; set; }
        public virtual MA_INSTANCIA MA_INSTANCIA2 { get; set; }
        public virtual MA_INSTITUCION MA_INSTITUCION { get; set; }
        public virtual ICollection<SG_PERSONA_TRABAJO> SG_PERSONA_TRABAJOS { get; set; }
    }
}
