//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Personal.Models;
    using System.Collections.Generic;

    [MetadataType(typeof(institutionModel))]

    public partial class MA_INSTITUCION
    {
        public MA_INSTITUCION()
        {
            this.MA_GRADO_MILITAR = new HashSet<MA_GRADO_MILITAR>();
            this.MA_INSTANCIA = new HashSet<MA_INSTANCIA>();
            this.MA_TIPO_INSTITUCION = new MA_TIPO_INSTITUCION();
            this.MA_TIPO_ENTIDAD = new MA_TIPO_ENTIDAD();
        }

        public Nullable<int> I_COD_TIPO_INSTITUCION { get; set; }
        public int I_COD_INSTITUCION { get; set; }
        public string V_DES_INSTITUCION { get; set; }
        public string V_ABREV_INSTITUCION { get; set; }
        public string C_ACTIVO { get; set; }
        public int I_COD_TIPO_ENTIDAD { get; set; }
        public virtual ICollection<MA_GRADO_MILITAR> MA_GRADO_MILITAR { get; set; }
        public virtual ICollection<MA_INSTANCIA> MA_INSTANCIA { get; set; }
        public virtual MA_TIPO_INSTITUCION MA_TIPO_INSTITUCION { get; set; }

        public virtual MA_TIPO_ENTIDAD MA_TIPO_ENTIDAD { get; set; }
    }
}
