//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_MESES
    {
        public MA_MESES()
        {
            this.MA_APERTURAR_MES_PEDIDO = new HashSet<MA_APERTURAR_MES_PEDIDO>();
        }
    
        public string V_DES_MES { get; set; }
        public int I_COD_MES { get; set; }
    
        public virtual ICollection<MA_APERTURAR_MES_PEDIDO> MA_APERTURAR_MES_PEDIDO { get; set; }
    }
}
