//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_MARCA_VEHICULO
    {
        public MA_MARCA_VEHICULO()
        {
            this.MA_MODELO_VEHICULOS = new HashSet<MA_MODELO_VEHICULOS>();
        }
    
        public int I_COD_MARCA_VEHICULO { get; set; }
        public string V_DES_MARCA_VEHICULO { get; set; }
        public string C_ACTIVO { get; set; }
    
        public virtual ICollection<MA_MODELO_VEHICULOS> MA_MODELO_VEHICULOS { get; set; }
    }
}
