//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_MENU_SISTEMA
    {
        public MA_MENU_SISTEMA()
        {
            this.MA_TIPO_PERFIL = new HashSet<MA_TIPO_PERFIL>();
        }
    
        public Nullable<int> I_NIVEL_MENU_APLICACION { get; set; }
        public string C_COD_MENU_SUPERIOR { get; set; }
        public string C_COD_TIPO_SISTEMA { get; set; }
        public string C_COD_MENU { get; set; }
        public string C_COD_MENU_SISTEMA { get; set; }
        public string C_TIPO_OPCION { get; set; }
        public string C_NAME_FORM { get; set; }
        public string V_DES_OPCION { get; set; }
        public Nullable<int> I_COD_TIPO_IMAGEN { get; set; }
        public string C_DES_DIRECTORIO_IMG { get; set; }
    
        public virtual MA_MENU MA_MENU { get; set; }
        public virtual MA_TIPO_SISTEMA MA_TIPO_SISTEMA { get; set; }
        public virtual MA_TIPO_IMAGENES MA_TIPO_IMAGENES { get; set; }
        public virtual ICollection<MA_TIPO_PERFIL> MA_TIPO_PERFIL { get; set; }
    }
}
