//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PREGUNTAS
    {
        public MA_PREGUNTAS()
        {
            this.SG_PERSONA_PREGUNTAS = new HashSet<SG_PERSONA_PREGUNTAS>();
        }
    
        public int I_COD_PREGUNTAS { get; set; }
        public string V_DES_PREGUNTAS { get; set; }
        public string C_ACTIVO { get; set; }
        public int I_COD_TIPO_PREGUNTAS { get; set; }
    
        public virtual MA_TIPO_PREGUNTAS MA_TIPO_PREGUNTAS { get; set; }
        public virtual ICollection<SG_PERSONA_PREGUNTAS> SG_PERSONA_PREGUNTAS { get; set; }
    }
}
