//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Personal.Models;
     

    [MetadataType(typeof(situacionMilitarModel))]
    public partial class MA_SITUACION_MILITAR
    {
        public MA_SITUACION_MILITAR()
        {
            this.RRHH_PERSONA_GRADO = new HashSet<RRHH_PERSONA_GRADO>();
        }
    
        public int I_COD_SITUACION_MILITAR { get; set; }
        public string V_DES_TIPO_SITUACION { get; set; }
        public string C_ACTIVO { get; set; }    
        public virtual ICollection<RRHH_PERSONA_GRADO> RRHH_PERSONA_GRADO { get; set; }


    }
}
