//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Personal.Models;
    using System.Collections.Generic;


    [MetadataType(typeof(TypeInstitutionModel))]
    public partial class MA_TIPO_INSTITUCION
    {
        public MA_TIPO_INSTITUCION()
        {
            this.MA_INSTITUCION = new HashSet<MA_INSTITUCION>();
        }
        public int I_COD_TIPO_INSTITUCION { get; set; }
        public string V_DES_TIPO_INSTITUCION { get; set; }
        public virtual ICollection<MA_INSTITUCION> MA_INSTITUCION { get; set; }

    }
}
