//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TIPO_IMAGENES
    {
        public MA_TIPO_IMAGENES()
        {
            this.MA_MENU_SISTEMA = new HashSet<MA_MENU_SISTEMA>();
            this.SG_PERSONA_IMAGENES = new HashSet<SG_PERSONA_IMAGENES>();
        }
    
        public int I_COD_TIPO_IMAGEN { get; set; }
        public string V_DES_TIPO_IMAGEN { get; set; }
        public string C_ACTIVO { get; set; }
    
        public virtual ICollection<MA_MENU_SISTEMA> MA_MENU_SISTEMA { get; set; }
        public virtual ICollection<SG_PERSONA_IMAGENES> SG_PERSONA_IMAGENES { get; set; }
    }
}
