//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TIPO_PEDIDO
    {
        public MA_TIPO_PEDIDO()
        {
            this.PED_PEDIDO_CABECERA = new HashSet<PED_PEDIDO_CABECERA>();
        }
    
        public int I_COD_TIPO_PEDIDO { get; set; }
        public string V_DES_TIPO_PEDIDO { get; set; }
    
        public virtual ICollection<PED_PEDIDO_CABECERA> PED_PEDIDO_CABECERA { get; set; }
    }
}
