//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using Personal.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(tipoModalidadModel))]
    public partial class MA_TIPO_MODALIDAD
    {
        public MA_TIPO_MODALIDAD()
        {
            this.RRHH_PERSONA_MODALIDAD = new HashSet<RRHH_PERSONA_MODALIDAD>();
            this.MA_TIPO_EMPLEADO = new MA_TIPO_EMPLEADO();
        }

        public int I_COD_TIPO_MODALIDAD { get; set; }
        public string V_DES_TIPO_MODALIDA { get; set; }
        public string C_ACTIVO { get; set; }
        public int I_COD_TIPO_EMPLEADO { get; set; }
        public virtual ICollection<RRHH_PERSONA_MODALIDAD> RRHH_PERSONA_MODALIDAD { get; set; }
        public virtual MA_TIPO_EMPLEADO MA_TIPO_EMPLEADO { get; set; }

    }
}
