//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TIPO_ARTICULO
    {
        public MA_TIPO_ARTICULO()
        {
            this.MA_ARTICULO = new HashSet<MA_ARTICULO>();
            this.PED_ARTICULO_AREAS = new HashSet<PED_ARTICULO_AREAS>();
        }
    
        public int I_COD_TIPO_ARTICULO { get; set; }
        public string V_DES_TIPO_ARTICULO { get; set; }
        public string C_ACTIVO { get; set; }
        public Nullable<System.DateTime> D_FECHA_REGISTRO { get; set; }
    
        public virtual ICollection<MA_ARTICULO> MA_ARTICULO { get; set; }
        public virtual ICollection<PED_ARTICULO_AREAS> PED_ARTICULO_AREAS { get; set; }
    }
}
