//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TIPO_PERFIL
    {
        public MA_TIPO_PERFIL()
        {
            this.PRV_USUARIO_PERFIL = new HashSet<PRV_USUARIO_PERFIL>();
            this.MA_MENU_SISTEMA = new HashSet<MA_MENU_SISTEMA>();
        }
    
        public int I_COD_TIPO_PERFIL { get; set; }
        public string V_DES_PERFIL { get; set; }
        public string C_ACTIVO { get; set; }
        public Nullable<System.DateTime> D_FEC_REGISTRO { get; set; }
        public Nullable<System.DateTime> D_FEC_BAJA { get; set; }
    
        public virtual ICollection<PRV_USUARIO_PERFIL> PRV_USUARIO_PERFIL { get; set; }
        public virtual ICollection<MA_MENU_SISTEMA> MA_MENU_SISTEMA { get; set; }
    }
}
