//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TIPO_SERVICIO_MILITAR
    {
        public int I_COD_TIPO_SERVICIO_MILITAR { get; set; }
        public string V_DES_TIPO_MILITAR { get; set; }
    }
}
