//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TIPO_SISTEMA
    {
        public MA_TIPO_SISTEMA()
        {
            this.MA_APERTURAR_AÑOS = new HashSet<MA_APERTURAR_AÑOS>();
            this.MA_MENU_SISTEMA = new HashSet<MA_MENU_SISTEMA>();
        }
    
        public string C_COD_TIPO_SISTEMA { get; set; }
        public string V_DES_TIPO_SISTEMA { get; set; }
        public string C_ACTIVO { get; set; }
        public string V_DES_HOST { get; set; }
        public Nullable<int> I_COD_TIPO_APLICACION { get; set; }
    
        public virtual ICollection<MA_APERTURAR_AÑOS> MA_APERTURAR_AÑOS { get; set; }
        public virtual ICollection<MA_MENU_SISTEMA> MA_MENU_SISTEMA { get; set; }
        public virtual MA_TIPO_APLICACION MA_TIPO_APLICACION { get; set; }
    }
}
