//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TIPO_PERSONA
    {
        public MA_TIPO_PERSONA()
        {
            this.RRHH_DET_PERSONA_TIPO = new HashSet<RRHH_DET_PERSONA_TIPO>();
        }
    
        public int I_COD_TIPO_PERSONA { get; set; }
        public string V_DES_TIPO_PERSONA { get; set; }
    
        public virtual ICollection<RRHH_DET_PERSONA_TIPO> RRHH_DET_PERSONA_TIPO { get; set; }
    }
}
