//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_UNIDAD_MEDIDA
    {
        public MA_UNIDAD_MEDIDA()
        {
            this.MA_ARTICULO = new HashSet<MA_ARTICULO>();
        }
    
        public int I_COD_UNIDAD_MEDIDA { get; set; }
        public string V_DES_UNIDAD_MEDIDA { get; set; }
        public string V_ABREV_UNIDAD { get; set; }
    
        public virtual ICollection<MA_ARTICULO> MA_ARTICULO { get; set; }
    }
}
