//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_PECOSA_ESTADO
    {
        public int I_COD_PECOSA_ESTADO { get; set; }
        public string C_COD_PECOSA { get; set; }
        public string C_COD_ESTADO_PECOSA { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
    
        public virtual MA_ESTADO_PECOSA MA_ESTADO_PECOSA { get; set; }
        public virtual PED_PEDIDO_PECOSA PED_PEDIDO_PECOSA { get; set; }
    }
}
