//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_ARTICULO_AREAS
    {
        public PED_ARTICULO_AREAS()
        {
            this.MA_ARTICULO = new HashSet<MA_ARTICULO>();
        }
    
        public Nullable<int> I_COD_TIPO_ARTICULO { get; set; }
        public string I_COD_INSTANCIA { get; set; }
        public string C_COD_AREA { get; set; }
        public string C_COD_AREA_SUPERIOR { get; set; }
        public int I_COD_PED_ARTICULO_AREA { get; set; }
    
        public virtual MA_INSTANCIA_AREAS MA_INSTANCIA_AREAS { get; set; }
        public virtual MA_TIPO_ARTICULO MA_TIPO_ARTICULO { get; set; }
        public virtual ICollection<MA_ARTICULO> MA_ARTICULO { get; set; }
    }
}
