//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_DET_VALE_RETIRO
    {
        public PED_DET_VALE_RETIRO()
        {
            this.PED_DET_VALE_RETIRO1 = new HashSet<PED_DET_VALE_RETIRO>();
            this.PED_PEDIDO_CABECERA = new HashSet<PED_PEDIDO_CABECERA>();
        }
    
        public Nullable<int> I_STOCK_SOLICITADO { get; set; }
        public string C_DEBE_ARTICULO { get; set; }
        public Nullable<decimal> D_PRECIO { get; set; }
        public string C_COD_DET_VALE_RETIRO { get; set; }
        public string C_COD_DET_VALE_RETIRO_SUPERIOR { get; set; }
        public string C_COD_VALE { get; set; }
        public string C_COD_ARTICULO { get; set; }
    
        public virtual MA_ARTICULO MA_ARTICULO { get; set; }
        public virtual PED_CAB_VALE_RETIRO PED_CAB_VALE_RETIRO { get; set; }
        public virtual ICollection<PED_DET_VALE_RETIRO> PED_DET_VALE_RETIRO1 { get; set; }
        public virtual PED_DET_VALE_RETIRO PED_DET_VALE_RETIRO2 { get; set; }
        public virtual ICollection<PED_PEDIDO_CABECERA> PED_PEDIDO_CABECERA { get; set; }
    }
}
