//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_PEDIDO_ESTADO
    {
        public string C_COD_PEDIDO { get; set; }
        public string I_COD_ESTADO_PEDIDO { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public int I_COD_USUARIO { get; set; }
        public int I_COD_PEDIDO_ESTADO { get; set; }
    
        public virtual MA_ESTADO_PEDIDO MA_ESTADO_PEDIDO { get; set; }
        public virtual PED_PEDIDO_CABECERA PED_PEDIDO_CABECERA { get; set; }
        public virtual PRV_USUARIO PRV_USUARIO { get; set; }
    }
}
