//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_CAB_VALE_RETIRO
    {
        public PED_CAB_VALE_RETIRO()
        {
            this.PED_CAB_ESTADO_VALE = new HashSet<PED_CAB_ESTADO_VALE>();
            this.PED_DET_VALE_RETIRO = new HashSet<PED_DET_VALE_RETIRO>();
        }
    
        public string C_COD_VALE { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string V_MOTIVO_PEDIDO { get; set; }
        public string I_COD_INSTANCIA { get; set; }
        public string C_COD_AREA { get; set; }
        public string C_COD_AREA_SUPERIOR { get; set; }
        public string C_COD_PERSONA { get; set; }
        public string C_COD_APERTURAR_MES_PEDIDO { get; set; }
        public string C_ESTADO_VALE { get; set; }
    
        public virtual MA_APERTURAR_MES_PEDIDO MA_APERTURAR_MES_PEDIDO { get; set; }
        public virtual MA_INSTANCIA_AREAS MA_INSTANCIA_AREAS { get; set; }
        public virtual ICollection<PED_CAB_ESTADO_VALE> PED_CAB_ESTADO_VALE { get; set; }
        public virtual RRHH_PERSONA RRHH_PERSONA { get; set; }
        public virtual ICollection<PED_DET_VALE_RETIRO> PED_DET_VALE_RETIRO { get; set; }
    }
}
