//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_PEDIDO_CABECERA
    {
        public PED_PEDIDO_CABECERA()
        {
            this.PED_PEDIDO_DETALLE = new HashSet<PED_PEDIDO_DETALLE>();
            this.PED_PEDIDO_ESTADO = new HashSet<PED_PEDIDO_ESTADO>();
            this.PED_PEDIDO_PECOSA = new HashSet<PED_PEDIDO_PECOSA>();
            this.PED_DET_VALE_RETIRO = new HashSet<PED_DET_VALE_RETIRO>();
        }
    
        public string C_COD_PEDIDO { get; set; }
        public string I_COD_INSTANCIA { get; set; }
        public string C_COD_AREA { get; set; }
        public string C_COD_AREA_SUPERIOR { get; set; }
        public Nullable<int> I_COD_TIPO_PEDIDO { get; set; }
        public string C_COD_APERTURAR_MES_PEDIDO { get; set; }
        public string V_OBSERVACION { get; set; }
    
        public virtual MA_APERTURAR_MES_PEDIDO MA_APERTURAR_MES_PEDIDO { get; set; }
        public virtual MA_INSTANCIA_AREAS MA_INSTANCIA_AREAS { get; set; }
        public virtual MA_TIPO_PEDIDO MA_TIPO_PEDIDO { get; set; }
        public virtual ICollection<PED_PEDIDO_DETALLE> PED_PEDIDO_DETALLE { get; set; }
        public virtual ICollection<PED_PEDIDO_ESTADO> PED_PEDIDO_ESTADO { get; set; }
        public virtual ICollection<PED_PEDIDO_PECOSA> PED_PEDIDO_PECOSA { get; set; }
        public virtual ICollection<PED_DET_VALE_RETIRO> PED_DET_VALE_RETIRO { get; set; }
    }
}
