//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_CAB_ESTADO_VALE
    {
        public string I_COD_ESTADO_PEDIDO { get; set; }
        public string C_COD_VALE { get; set; }
        public int I_COD_USUARIO { get; set; }
        public Nullable<System.DateTime> D_FEC_REGISTRO { get; set; }
        public int I_COD_VALE_ESTADO { get; set; }
    
        public virtual MA_ESTADO_PEDIDO MA_ESTADO_PEDIDO { get; set; }
        public virtual PED_CAB_VALE_RETIRO PED_CAB_VALE_RETIRO { get; set; }
        public virtual PRV_USUARIO PRV_USUARIO { get; set; }
    }
}
