//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_PEDIDO_DETALLE
    {
        public string C_COD_ARTICULO { get; set; }
        public string C_COD_PEDIDO { get; set; }
        public Nullable<int> I_STOCK_SOLICITADO { get; set; }
        public Nullable<int> I_STOCK_APROB_ALMACEN { get; set; }
        public Nullable<int> I_STOCK_APROB_DIREJE { get; set; }
        public Nullable<decimal> D_PRECIO { get; set; }
        public string C_ACTIVO { get; set; }
        public Nullable<int> I_TOTAL_ATENDER { get; set; }
        public Nullable<int> I_TOTAL_ADELANTADO { get; set; }
        public Nullable<int> I_TOTAL_PENDIENTES { get; set; }
    
        public virtual MA_ARTICULO MA_ARTICULO { get; set; }
        public virtual PED_PEDIDO_CABECERA PED_PEDIDO_CABECERA { get; set; }
    }
}
