//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRV_USUARIO
    {
        public PRV_USUARIO()
        {
            this.PED_CAB_ESTADO_VALE = new HashSet<PED_CAB_ESTADO_VALE>();
            this.PED_PEDIDO_ESTADO = new HashSet<PED_PEDIDO_ESTADO>();
            this.PRV_USUARIO_PERFIL = new HashSet<PRV_USUARIO_PERFIL>();
            this.PRV_USUARIO_ESTADO = new HashSet<PRV_USUARIO_ESTADO>();
        }
    
        public int I_COD_USUARIO { get; set; }
        public string V_NOM_USUARIO { get; set; }
        public string C_COD_PERSONA { get; set; }
        public string V_CONTRASEÑA { get; set; }
    
        public virtual ICollection<PED_CAB_ESTADO_VALE> PED_CAB_ESTADO_VALE { get; set; }
        public virtual ICollection<PED_PEDIDO_ESTADO> PED_PEDIDO_ESTADO { get; set; }
        public virtual RRHH_PERSONA RRHH_PERSONA { get; set; }
        public virtual ICollection<PRV_USUARIO_PERFIL> PRV_USUARIO_PERFIL { get; set; }
        public virtual ICollection<PRV_USUARIO_ESTADO> PRV_USUARIO_ESTADO { get; set; }
    }
}
