//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRV_USUARIO_ESTADO
    {
        public int I_COD_TIPO_ESTADO { get; set; }
        public int I_COD_USUARIO { get; set; }
        public Nullable<System.DateTime> D_FEC_REGISTRO { get; set; }
        public Nullable<System.DateTime> D_FEC_BAJA { get; set; }
        public string C_ACTIVO { get; set; }
    
        public virtual MA_TIPO_ESTADO MA_TIPO_ESTADO { get; set; }
        public virtual PRV_USUARIO PRV_USUARIO { get; set; }
    }
}
