//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Personal.Models;
    using System.Collections.Generic;

    [MetadataType(typeof(peopleChargeModel))]

    public partial class RRHH_PERSONA_CARGO
    {
        public Nullable<int> I_COD_CARGO { get; set; }
        public string C_COD_PERSONA { get; set; }
        public int I_COD_PERSONA_CARGO { get; set; }
        public string D_FEC_REGISTRO { get; set; }
        //public Nullable<System.DateTime> D_FEC_BAJA { get; set; }

        public Nullable<System.DateTime> D_FEC_BAJA { get; set; }
        public string C_ACTIVO { get; set; }
        public string I_COD_INSTANCIA { get; set; }
        public string C_COD_AREA { get; set; }
        public string C_COD_AREA_SUPERIOR { get; set; }
        public string V_OBSERVACION_INGRESO { get; set; }
        public string V_OBSERVACION_ANULADO { get; set; }
        public DateTime? D_FEC_INGRESO { get; set; }
        public virtual MA_CARGO MA_CARGO { get; set; }
        public virtual MA_INSTANCIA_AREAS MA_INSTANCIA_AREAS { get; set; }
        public virtual RRHH_PERSONA RRHH_PERSONA { get; set; }
    }
}
