//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;

    public partial class RRHH_PERSONA_GRADO
    {
        public string C_COD_GRADO_MILITAR { get; set; }
        public string C_COD_PERSONA { get; set; }
        public int I_COD_PERSONA_GRADO { get; set; }
        public Nullable<int> I_COD_SITUACION_MILITAR { get; set; }
        public Nullable<System.DateTime> D_FECHA_REGISTRO { get; set; }
        public Nullable<System.DateTime> D_FECHA_BAJA { get; set; }
        public string C_ACTIVO { get; set; }
        public Nullable<int> I_COD_INSTITUCION { get; set; }
        public string V_OBSERVACION { get; set; }
        public virtual MA_GRADO_MILITAR MA_GRADO_MILITAR { get; set; }
        public virtual MA_SITUACION_MILITAR MA_SITUACION_MILITAR { get; set; }
        public virtual RRHH_PERSONA RRHH_PERSONA { get; set; }
    }
}
