//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_DET_PERSONA_TIPO
    {
        public string C_COD_PERSONA { get; set; }
        public int I_COD_TIPO_PERSONA { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string FEC_BAJA { get; set; }
        public string C_ACTIVO { get; set; }
    
        public virtual MA_TIPO_PERSONA MA_TIPO_PERSONA { get; set; }
        public virtual RRHH_PERSONA RRHH_PERSONA { get; set; }
    }
}
