//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using Personal.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(personaDetalleModel))]
    public partial class RRHH_PERSONA_DETALLE
    {
        public RRHH_PERSONA_DETALLE()
        {

            this.MA_ESTADO_CIVIL = new MA_ESTADO_CIVIL();
            this.MA_GRUPO_SANGUINEO = new MA_GRUPO_SANGUINEO();
            this.MA_SEXO = new MA_SEXO();
            this.RRHH_PERSONA = new RRHH_PERSONA();
            this.MA_PAIS = new MA_PAI();
            this.MA_DEPARTAMENTO = new MA_DEPARTAMENTO();
            this.MA_PROVINCIA = new MA_PROVINCIA();
            this.MA_DISTRITO = new MA_DISTRITO();

        }
        public string C_COD_DISTRITO { get; set; }
        public Nullable<int> I_COD_PAIS { get; set; }
        public string C_COD_PROVINCIA { get; set; }
        public string C_COD_DEPARTAMENTO { get; set; }
        public Nullable<int> I_COD_ESTADO_CIVIL { get; set; }
        public Nullable<int> I_COD_SEXO { get; set; }
        public Nullable<int> I_COD_GRUPO_SANGUINEO { get; set; }
        public Nullable<int> I_PESO { get; set; }
        public Nullable<decimal> DE_TALLA { get; set; }
        public string C_COD_PERSONA { get; set; }
        public int I_COD_PERSONA_DETALLE { get; set; }
        public Nullable<System.DateTime> D_FEC_NACIMIENTO { get; set; }

        public virtual MA_ESTADO_CIVIL MA_ESTADO_CIVIL { get; set; }
        public virtual MA_GRUPO_SANGUINEO MA_GRUPO_SANGUINEO { get; set; }
        public virtual MA_SEXO MA_SEXO { get; set; }
        public virtual RRHH_PERSONA RRHH_PERSONA { get; set; }
        public virtual MA_DISTRITO MA_DISTRITO { get; set; }

        public virtual MA_PAI MA_PAIS { get; set; }
        public virtual MA_DEPARTAMENTO MA_DEPARTAMENTO { get; set; }
        public virtual MA_PROVINCIA MA_PROVINCIA { get; set; }
    }
}
