//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using Personal.Models;
    using System.Collections.Generic;

    [MetadataType(typeof(personaModel))]
    public partial class RRHH_PERSONA
    {
        public RRHH_PERSONA()
        {
            this.PED_CAB_VALE_RETIRO = new HashSet<PED_CAB_VALE_RETIRO>();
            this.PRV_USUARIO = new HashSet<PRV_USUARIO>();
            this.RRHH_DET_PERSONA_TIPO = new HashSet<RRHH_DET_PERSONA_TIPO>();
            this.SG_PERSONA_PREGUNTAS = new HashSet<SG_PERSONA_PREGUNTAS>();
            this.SG_PERSONA_ARMAS = new HashSet<SG_PERSONA_ARMAS>();
            this.SG_PERSONA_IMAGENES = new HashSet<SG_PERSONA_IMAGENES>();
            this.SG_CAB_PERSONA_FAMILIAR = new HashSet<SG_CAB_PERSONA_FAMILIAR>();
            this.RRHH_PERSONA_GRADO = new HashSet<RRHH_PERSONA_GRADO>();
            this.RRHH_PERSONA_MODALIDAD = new HashSet<RRHH_PERSONA_MODALIDAD>();
            this.RRHH_PERSONA_IDENTIFICACION = new HashSet<RRHH_PERSONA_IDENTIFICACION>();
            this.RRHH_PERSONA_DETALLE = new HashSet<RRHH_PERSONA_DETALLE>();
            this.SG_PERSONA_RAZGOS = new HashSet<SG_PERSONA_RAZGOS>();
            this.SG_PERSONA_SEÑALES = new HashSet<SG_PERSONA_SEÑALES>();
            this.RRHH_PERSONA_CARGO = new HashSet<RRHH_PERSONA_CARGO>();
            this.SG_PERSONA_TRABAJOS = new HashSet<SG_PERSONA_TRABAJO>();
            this.SG_PERSONA_ESTUDIOS = new HashSet<SG_PERSONA_ESTUDIOS>();
            this.RRHH_PERSONA_DOMICILIO = new HashSet<RRHH_PERSONA_DOMICILIO>();
            this.SG_PERSONA_VIAJES = new HashSet<SG_PERSONA_VIAJES>();
            this.RRHH_PERSONA_TELEFONO = new HashSet<RRHH_PERSONA_TELEFONO>();
            this.SG_PERSONA_VEHICULOS = new HashSet<SG_PERSONA_VEHICULOS>();
        }

        public string C_COD_PERSONA { get; set; }
        public string V_APELLIDO_PATERNO { get; set; }
        public string V_APELLIDO_MATERNO { get; set; }
        public string V_NOMBRES { get; set; }
        public string C_ACTIVO { get; set; }

        public virtual ICollection<PED_CAB_VALE_RETIRO> PED_CAB_VALE_RETIRO { get; set; }
        public virtual ICollection<PRV_USUARIO> PRV_USUARIO { get; set; }
        public virtual ICollection<RRHH_DET_PERSONA_TIPO> RRHH_DET_PERSONA_TIPO { get; set; }
        public virtual ICollection<SG_PERSONA_PREGUNTAS> SG_PERSONA_PREGUNTAS { get; set; }
        public virtual ICollection<SG_PERSONA_ARMAS> SG_PERSONA_ARMAS { get; set; }
        public virtual ICollection<SG_PERSONA_IMAGENES> SG_PERSONA_IMAGENES { get; set; }
        public virtual ICollection<SG_CAB_PERSONA_FAMILIAR> SG_CAB_PERSONA_FAMILIAR { get; set; }
        public virtual ICollection<RRHH_PERSONA_GRADO> RRHH_PERSONA_GRADO { get; set; }
        public virtual ICollection<RRHH_PERSONA_MODALIDAD> RRHH_PERSONA_MODALIDAD { get; set; }
        public virtual ICollection<RRHH_PERSONA_IDENTIFICACION> RRHH_PERSONA_IDENTIFICACION { get; set; }
        public virtual ICollection<RRHH_PERSONA_DETALLE> RRHH_PERSONA_DETALLE { get; set; }
        public virtual ICollection<SG_PERSONA_RAZGOS> SG_PERSONA_RAZGOS { get; set; }
        public virtual ICollection<SG_PERSONA_SEÑALES> SG_PERSONA_SEÑALES { get; set; }
        public virtual ICollection<RRHH_PERSONA_CARGO> RRHH_PERSONA_CARGO { get; set; }
        public virtual ICollection<SG_PERSONA_TRABAJO> SG_PERSONA_TRABAJOS { get; set; }
        public virtual ICollection<SG_PERSONA_ESTUDIOS> SG_PERSONA_ESTUDIOS { get; set; }
        public virtual ICollection<RRHH_PERSONA_DOMICILIO> RRHH_PERSONA_DOMICILIO { get; set; }
        public virtual ICollection<SG_PERSONA_VIAJES> SG_PERSONA_VIAJES { get; set; }
        public virtual ICollection<RRHH_PERSONA_TELEFONO> RRHH_PERSONA_TELEFONO { get; set; }
        public virtual ICollection<SG_PERSONA_VEHICULOS> SG_PERSONA_VEHICULOS { get; set; }
    }
}
