//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    using System.Data.Spatial;
    
    public partial class RRHH_PERSONA_DOMICILIO
    {
        public string C_COD_PERSONA { get; set; }
        public string C_COD_DISTRITO { get; set; }
        public Nullable<int> I_COD_PAIS { get; set; }
        public string C_COD_PROVINCIA { get; set; }
        public string C_COD_DEPARTAMENTO { get; set; }
        public Nullable<int> I_COD_TIPO_DOMICILIO { get; set; }
        public string V_DES_DIRECCION { get; set; }
        public string V_DES_URBANIZACION { get; set; }
        public int I_COD_PERSONA_DOMICILIO { get; set; }
        public DbGeography V_GEO_LOCALIZACION { get; set; }
        public Nullable<System.DateTime> D_FEC_REGISTRO { get; set; }
        public Nullable<System.DateTime> D_FEC_BAJA { get; set; }
        public string C_ACTIVO { get; set; }
    
        public virtual MA_TIPO_DOMICILIO MA_TIPO_DOMICILIO { get; set; }
        public virtual RRHH_PERSONA RRHH_PERSONA { get; set; }
    }
}
