//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_CAB_PERSONA_FAMILIAR
    {
        public SG_CAB_PERSONA_FAMILIAR()
        {
            this.SG_CAB_PERSONA_FAMILIAR1 = new HashSet<SG_CAB_PERSONA_FAMILIAR>();
            this.SG_DET_PERSONA_FAMILIAR = new HashSet<SG_DET_PERSONA_FAMILIAR>();
        }
    
        public string C_COD_FAMILIAR { get; set; }
        public string C_COD_GRUPO_FAMILIAR { get; set; }
        public string C_COD_PERSONA { get; set; }
    
        public virtual RRHH_PERSONA RRHH_PERSONA { get; set; }
        public virtual ICollection<SG_CAB_PERSONA_FAMILIAR> SG_CAB_PERSONA_FAMILIAR1 { get; set; }
        public virtual SG_CAB_PERSONA_FAMILIAR SG_CAB_PERSONA_FAMILIAR2 { get; set; }
        public virtual ICollection<SG_DET_PERSONA_FAMILIAR> SG_DET_PERSONA_FAMILIAR { get; set; }
    }
}
