//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG_DET_PERSONA_FAMILIAR
    {
        public Nullable<int> I_COD_OCUPACION { get; set; }
        public string C_COD_FAMILIAR { get; set; }
        public int I_COD_TIPO_FAMILIAR { get; set; }
        public string C_COD_PERSONA_FAMILIAR { get; set; }
        public string C_ACTIVO { get; set; }
    
        public virtual MA_OCUPACION MA_OCUPACION { get; set; }
        public virtual MA_TIPO_FAMILIAR MA_TIPO_FAMILIAR { get; set; }
        public virtual SG_CAB_PERSONA_FAMILIAR SG_CAB_PERSONA_FAMILIAR { get; set; }
    }
}
