//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntity
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Personal.Models;
    using System.Collections.Generic;

    [MetadataType(typeof(peopleStudiesModel))]
    public partial class SG_PERSONA_ESTUDIOS
    {
        public SG_PERSONA_ESTUDIOS()
        {
            this.MA_ESPECIALIDAD = new MA_ESPECIALIDAD();
            this.MA_GRADO_ACADEMICO = new MA_GRADO_ACADEMICO();
            this.MA_CARRERA_PROFESIONALES = new MA_CARRERA_PROFESIONALES();
            this.RRHH_PERSONA = new RRHH_PERSONA();
            this.MA_INSTITUCION = new MA_INSTITUCION();
        }
        public int I_COD_PERSONA_ESTUDIOS { get; set; }
        public string C_COD_PERSONA { get; set; }
        public Nullable<int> I_COD_INSTITUCION { get; set; }
        public Nullable<int> I_COD_CARRERA_PROFESIONAL { get; set; }
        public Nullable<int> I_AÑO_INGRESO { get; set; }
        public Nullable<int> I_AÑO_EGRESO { get; set; }
        public Nullable<int> C_COD_GRADO_ACADEMICO { get; set; }
        public Nullable<int> I_COD_ESPECIALIDAD { get; set; }
        public string C_ACTIVO { get; set; }

        public virtual MA_ESPECIALIDAD MA_ESPECIALIDAD { get; set; }
        public virtual MA_GRADO_ACADEMICO MA_GRADO_ACADEMICO { get; set; }
        public virtual MA_CARRERA_PROFESIONALES MA_CARRERA_PROFESIONALES { get; set; }
        public virtual RRHH_PERSONA RRHH_PERSONA { get; set; }
        public virtual MA_INSTITUCION MA_INSTITUCION { get; set; }
    }
}
